name: Actions
run-name: Test, build and release
on:
  push:
    tags:
      - "*"
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - uses: actions/checkout@v4
      - name: Build
        run: dotnet build --configuration Release
      - name: Pack nuget package
        run: dotnet pack --configuration Release /p:Version=${{ github.ref_name }} --no-build --output .
      - name: Publish to nuget
        run: dotnet nuget push PureUpgrader.${{ github.ref_name }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json